// react-frontend/src/components/plan/CalendarView.tsx
/**
 * ============================================================================
 * CalendarView.tsx — 日历视图组件
 * ============================================================================
 *
 * 【组件说明】
 * 以月历形式展示每日任务的日历视图组件。
 *
 * 【主要功能】
 * - 月份切换
 * - 日期选择高亮
 * - 每日任务预览
 * - 任务状态标识
 * - emit 事件通知父组件
 * ============================================================================
 */

import React, { useState, useMemo, useEffect } from 'react'
import { Button, Modal, Tag, Spin } from 'antd'
import { LeftOutlined, RightOutlined, CheckOutlined, ClockCircleOutlined, CloseCircleOutlined } from '@ant-design/icons'
import { planApi, type PlanItem } from '@/api/plan'
import dayjs, { Dayjs } from 'dayjs'
import './CalendarView.css'

interface CalendarDay {
  date: string
  day: number
  isOtherMonth: boolean
  isToday: boolean
  plans: PlanItem[]
}

interface CalendarViewProps {
  onSelectDate?: (date: string) => void
}

const weekDays = ['日', '一', '二', '三', '四', '五', '六']

const categories = [
  { value: 'WORK', label: '工作' },
  { value: 'STUDY', label: '学习' },
  { value: 'LIFE', label: '生活' },
  { value: 'HEALTH', label: '健康' }
]

const statusMap: Record<string, { label: string; color: string }> = {
  'TODO': { label: '待完成', color: 'default' },
  'IN_PROGRESS': { label: '进行中', color: 'processing' },
  'DONE': { label: '已完成', color: 'success' },
  'CANCELLED': { label: '已取消', color: 'error' }
}

const repeatTypeMap: Record<string, string> = {
  'NONE': '不重复',
  'DAILY': '每天',
  'WEEKLY': '每周',
  'MONTHLY': '每月',
  'CUSTOM': '自定义'
}

const priorityColors: Record<string, string> = {
  'P0': '#ef4444',
  'P1': '#f97316',
  'P2': '#3b82f6',
  'P3': '#6b7280'
}

const CalendarView: React.FC<CalendarViewProps> = ({ onSelectDate }) => {
  // ============================================================================
  // // 状态
  // ============================================================================
  const [currentMonth, setCurrentMonth] = useState<Dayjs>(dayjs())
  const [selectedDate, setSelectedDate] = useState<string>(dayjs().format('YYYY-MM-DD'))
  const [selectedPlan, setSelectedPlan] = useState<PlanItem | null>(null)
  const [showPlanDialog, setShowPlanDialog] = useState(false)
  const [calendarPlans, setCalendarPlans] = useState<Record<string, PlanItem[]>>({})
  const [loadingPlans, setLoadingPlans] = useState(false)

  // ============================================================================
  // // 计算属性
  // ============================================================================
  const currentMonthYear = useMemo(() => {
    return currentMonth.format('YYYY 年 MM 月')
  }, [currentMonth])

  const selectedDayPlans = useMemo(() => {
    return calendarPlans[selectedDate] || []
  }, [calendarPlans, selectedDate])

  const calendarDays = useMemo((): CalendarDay[] => {
    const days: CalendarDay[] = []
    const firstDay = currentMonth.startOf('month')
    const lastDay = currentMonth.endOf('month')
    const startWeekday = firstDay.day()
    const endWeekday = lastDay.day()

    // 上个月的日期
    const prevMonth = currentMonth.subtract(1, 'month')
    const prevMonthLastDay = prevMonth.endOf('month')
    for (let i = startWeekday - 1; i >= 0; i--) {
      const day = prevMonthLastDay.subtract(i, 'day')
      days.push({
        date: day.format('YYYY-MM-DD'),
        day: day.date(),
        isOtherMonth: true,
        isToday: day.isSame(dayjs(), 'day'),
        plans: calendarPlans[day.format('YYYY-MM-DD')] || []
      })
    }

    // 当前月的日期
    for (let i = 1; i <= lastDay.date(); i++) {
      const day = firstDay.date(i)
      days.push({
        date: day.format('YYYY-MM-DD'),
        day: i,
        isOtherMonth: false,
        isToday: day.isSame(dayjs(), 'day'),
        plans: calendarPlans[day.format('YYYY-MM-DD')] || []
      })
    }

    // 下个月的日期
    const nextMonth = currentMonth.add(1, 'month')
    for (let i = 1; i <= 6 - endWeekday; i++) {
      const day = nextMonth.date(i)
      days.push({
        date: day.format('YYYY-MM-DD'),
        day: i,
        isOtherMonth: true,
        isToday: day.isSame(dayjs(), 'day'),
        plans: calendarPlans[day.format('YYYY-MM-DD')] || []
      })
    }

    return days
  }, [currentMonth, calendarPlans])

  // ============================================================================
  // // 辅助函数
  // ============================================================================
  const categoryLabel = (val: string) => {
    return categories.find(c => c.value === val)?.label || val
  }

  const statusLabel = (val: string) => {
    return statusMap[val]?.label || val
  }

  const repeatTypeLabel = (val: string) => {
    return repeatTypeMap[val] || val
  }

  const subtaskProgress = (plan: PlanItem) => {
    if (!plan.subtaskCount || plan.subtaskCount === 0) return 0
    return Math.round(((plan.completedSubtaskCount || 0) / plan.subtaskCount) * 100)
  }

  // ============================================================================
  // // 导航
  // ============================================================================
  const prevMonth = () => {
    setCurrentMonth(currentMonth.subtract(1, 'month'))
  }

  const nextMonth = () => {
    setCurrentMonth(currentMonth.add(1, 'month'))
  }

  const goToToday = () => {
    setCurrentMonth(dayjs())
    const today = dayjs().format('YYYY-MM-DD')
    selectDate({ date: today, day: dayjs().date(), isOtherMonth: false, isToday: true, plans: [] })
  }

  const selectDate = (day: CalendarDay) => {
    setSelectedDate(day.date)
    onSelectDate?.(day.date)
  }

  // ============================================================================
  // // 数据加载
  // ============================================================================
  /**
   * 加载当月所有日期的任务数据
   *
   * 功能说明：批量加载当前月份每一天的任务列表
   * 业务逻辑：
   * 1. 获取当月第一天和最后一天日期
   * 2. 创建日期数组用于存储所有请求
   * 3. 循环为每一天创建一个API请求
   * 4. 使用Promise.all并行请求所有数据
   * 5. 将结果整理为以日期为key的对象结构：{ '2024-01-01': [Task1, Task2], ... }
   *
   * 使用场景：组件初始化、切换月份时调用
   */
  const loadMonthPlans = async () => {
    setLoadingPlans(true)
    try {
      const startDate = currentMonth.startOf('month').format('YYYY-MM-DD')
      const endDate = currentMonth.endOf('month').format('YYYY-MM-DD')

      // 加载当前月所有日期的任务
      const promises: Promise<PlanItem[]>[] = []
      let current = dayjs(startDate)
      while (!current.isAfter(dayjs(endDate))) {
        promises.push(planApi.list(current.format('YYYY-MM-DD')))
        current = current.add(1, 'day')
      }

      const results = await Promise.all(promises)
      const newCalendarPlans: Record<string, PlanItem[]> = {}
      let idx = 0
      current = dayjs(startDate)
      while (!current.isAfter(dayjs(endDate))) {
        newCalendarPlans[current.format('YYYY-MM-DD')] = results[idx] || []
        current = current.add(1, 'day')
        idx++
      }

      setCalendarPlans(newCalendarPlans)
    } catch (error) {
      console.error('Failed to load month plans', error)
    } finally {
      setLoadingPlans(false)
    }
  }

  // ============================================================================
  // // 交互处理
  // ============================================================================
  const handlePlanClick = (plan: PlanItem, e: React.MouseEvent) => {
    e.stopPropagation()
    setSelectedPlan(plan)
    setShowPlanDialog(true)
  }

  const handleCreatePlan = () => {
    onSelectDate?.(selectedDate)
    // 触发父组件打开新建任务弹窗
    Modal.info({ title: '提示', content: '请在任务列表中创建新任务' })
  }

  const showMorePlans = (day: CalendarDay) => {
    selectDate(day)
  }

  const editPlan = () => {
    onSelectDate?.(selectedDate)
    setShowPlanDialog(false)
    // 触发父组件打开编辑任务弹窗
    Modal.info({ title: '提示', content: '请在任务列表中编辑任务' })
  }

  const deletePlan = async () => {
    if (!selectedPlan) return

    Modal.confirm({
      title: '提示',
      content: '确认删除此任务？',
      okType: 'danger',
      onOk: async () => {
        try {
          await planApi.delete(selectedPlan.id)
          Modal.success({ content: '删除成功' })
          setShowPlanDialog(false)
          setSelectedPlan(null)
          loadMonthPlans()
        } catch (error) {
          console.error('Failed to delete plan', error)
        }
      }
    })
  }

  // ============================================================================
  // // 生命周期
  // ============================================================================
  useEffect(() => {
    setSelectedDate(dayjs().format('YYYY-MM-DD'))
    loadMonthPlans()
  }, [currentMonth])

  // ============================================================================
  // // 渲染
  // ============================================================================
  return (
    <div className="calendar-view">
      {/* 月份切换 */}
      <div className="calendar-header">
        <Button.Group>
          <Button icon={<LeftOutlined />} onClick={prevMonth}>上个月</Button>
          <Button icon={<RightOutlined />} onClick={nextMonth}>下个月</Button>
        </Button.Group>
        <div className="current-month">{currentMonthYear}</div>
        <Button onClick={goToToday}>今天</Button>
      </div>

      {/* 日历网格 */}
      <div className="calendar-grid">
        {/* 星期头 */}
        <div className="week-header">
          {weekDays.map(day => (
            <div key={day} className="weekday">{day}</div>
          ))}
        </div>

        {/* 日期格子 */}
        <div className="calendar-body">
          {calendarDays.map((day, idx) => (
            <div
              key={idx}
              className={`calendar-day ${day.isOtherMonth ? 'other-month' : ''} ${day.isToday ? 'today' : ''} ${selectedDate === day.date ? 'selected' : ''}`}
              onClick={() => selectDate(day)}
            >
              <div className="day-number">{day.day}</div>
              <div className="day-plans">
                {day.plans.slice(0, 3).map(plan => (
                  <div
                    key={plan.id}
                    className={`plan-chip priority-${plan.priority.toLowerCase()} ${plan.status === 'DONE' ? 'done' : ''}`}
                    onClick={(e) => handlePlanClick(plan, e)}
                    style={{ borderLeftColor: priorityColors[plan.priority] }}
                  >
                    <span className="plan-title">{plan.title}</span>
                    {plan.subtaskCount && plan.subtaskCount > 0 && (
                      <span className="plan-subtask">
                        {plan.completedSubtaskCount || 0}/{plan.subtaskCount}
                      </span>
                    )}
                  </div>
                ))}
                {day.plans.length > 3 && (
                  <div className="more-plans" onClick={(e) => { e.stopPropagation(); showMorePlans(day) }}>
                    +{day.plans.length - 3} 更多
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 选中日期的任务列表 */}
      {selectedDate && (
        <div className="day-details">
          <div className="details-header">
            <h3>{selectedDate} 的任务</h3>
            <Button type="primary" size="small" onClick={handleCreatePlan}>新增任务</Button>
          </div>
          <Spin spinning={loadingPlans}>
            <div className="day-plans-list">
              {selectedDayPlans.map(plan => (
                <div
                  key={plan.id}
                  className={`plan-item ${plan.status === 'DONE' ? 'done' : ''}`}
                  onClick={() => handlePlanClick(plan, {} as React.MouseEvent)}
                >
                  <div className="plan-info">
                    <div className="plan-main">
                      <Tag className="plan-priority" color={priorityColors[plan.priority]}>{plan.priority}</Tag>
                      <span className="plan-title">{plan.title}</span>
                    </div>
                    <div className="plan-meta">
                      <span className="plan-category">{categoryLabel(plan.category)}</span>
                      {plan.estimatedMins && <span>⏱ {plan.estimatedMins}min</span>}
                    </div>
                  </div>
                  <div className="plan-status">
                    {plan.status === 'DONE' && <CheckOutlined className="status-icon done" />}
                    {plan.status === 'IN_PROGRESS' && <ClockCircleOutlined className="status-icon inprogress" />}
                    {plan.status === 'TODO' && <CloseCircleOutlined className="status-icon todo" />}
                  </div>
                </div>
              ))}
              {selectedDayPlans.length === 0 && (
                <div className="empty-state">该日期暂无任务</div>
              )}
            </div>
          </Spin>
        </div>
      )}

      {/* 任务详情弹窗 */}
      <Modal
        open={showPlanDialog}
        title={selectedPlan ? '任务详情' : '新增任务'}
        width={600}
        onCancel={() => setShowPlanDialog(false)}
        footer={
          <>
            <Button onClick={() => setShowPlanDialog(false)}>关闭</Button>
            {selectedPlan && <Button type="primary" onClick={editPlan}>编辑</Button>}
            {selectedPlan && <Button danger onClick={deletePlan}>删除</Button>}
          </>
        }
        destroyOnClose
      >
        {selectedPlan && (
          <div className="plan-detail">
            <div className="detail-header">
              <Tag className="detail-priority" color={priorityColors[selectedPlan.priority]}>
                {selectedPlan.priority}
              </Tag>
              <h2>{selectedPlan.title}</h2>
            </div>
            {selectedPlan.description && <div className="detail-desc">{selectedPlan.description}</div>}
            <div className="detail-meta">
              <div className="meta-item">
                <span className="meta-label">分类:</span>
                <span>{categoryLabel(selectedPlan.category)}</span>
              </div>
              <div className="meta-item">
                <span className="meta-label">状态:</span>
                <Tag color={statusMap[selectedPlan.status]?.color}>{statusLabel(selectedPlan.status)}</Tag>
              </div>
              {selectedPlan.estimatedMins && (
                <div className="meta-item">
                  <span className="meta-label">预估:</span>
                  <span>{selectedPlan.estimatedMins} 分钟</span>
                </div>
              )}
              {selectedPlan.startTime && selectedPlan.endTime && (
                <div className="meta-item">
                  <span className="meta-label">时间:</span>
                  <span>{selectedPlan.startTime} - {selectedPlan.endTime}</span>
                </div>
              )}
              {selectedPlan.repeatType && (
                <div className="meta-item">
                  <span className="meta-label">重复:</span>
                  <span>{repeatTypeLabel(selectedPlan.repeatType)}</span>
                </div>
              )}
            </div>
            {selectedPlan.subtaskCount && selectedPlan.subtaskCount > 0 && (
              <div className="detail-subtasks">
                <div className="subtask-header">
                  <span>子任务进度</span>
                  <span>{selectedPlan.completedSubtaskCount || 0} / {selectedPlan.subtaskCount}</span>
                </div>
                <div className="subtask-progress">
                  <div className="progress-bar">
                    <div className="progress-fill" style={{ width: `${subtaskProgress(selectedPlan)}%` }}></div>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </Modal>
    </div>
  )
}

export default CalendarView

// frontend/src/views/plan/CalendarView.vue
<!--
/**
 * ============================================================================
 * CalendarView.vue — 日历视图组件
 * ============================================================================
 *
 * 【组件说明】
 * 以月历形式展示每日任务的日历视图组件。
 *
 * 【主要功能】
 * - 月份切换
 * - 日期选择高亮
 * - 每日任务预览
 * - 任务状态标识
 * - emit 事件通知父组件
 * ============================================================================
 */
-->

<template>
  <div class="calendar-view">
    <!-- 月份切换 -->
    <div class="calendar-header">
      <el-button-group>
        <el-button :icon="ArrowLeft" @click="prevMonth">上个月</el-button>
        <el-button :icon="ArrowRight" @click="nextMonth">下个月</el-button>
      </el-button-group>
      <div class="current-month">{{ currentMonthYear }}</div>
      <el-button @click="goToToday">今天</el-button>
    </div>

    <!-- 日历网格 -->
    <div class="calendar-grid">
      <!-- 星期头 -->
      <div class="week-header">
        <div v-for="day in weekDays" :key="day" class="weekday">{{ day }}</div>
      </div>

      <!-- 日期格子 -->
      <div class="calendar-body">
        <div
          v-for="(day, idx) in calendarDays"
          :key="idx"
          class="calendar-day"
          :class="{
            'other-month': day.isOtherMonth,
            'today': day.isToday,
            'selected': selectedDate === day.date
          }"
          @click="selectDate(day)"
        >
          <div class="day-number">{{ day.day }}</div>
          <div class="day-plans">
            <div
              v-for="plan in day.plans.slice(0, 3)"
              :key="plan.id"
              class="plan-chip"
              :class="[
                `priority-${plan.priority.toLowerCase()}`,
                { done: plan.status === 'DONE' }
              ]"
              @click.stop="handlePlanClick(plan)"
            >
              <span class="plan-title">{{ plan.title }}</span>
              <span v-if="plan.subtaskCount && plan.subtaskCount > 0" class="plan-subtask">
                {{ plan.completedSubtaskCount || 0 }}/{{ plan.subtaskCount }}
              </span>
            </div>
            <div v-if="day.plans.length > 3" class="more-plans" @click.stop="showMorePlans(day)">
              +{{ day.plans.length - 3 }} 更多
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 选中日期的任务列表 -->
    <div v-if="selectedDate" class="day-details">
      <div class="details-header">
        <h3>{{ selectedDate }} 的任务</h3>
        <el-button size="small" type="primary" @click="handleCreatePlan">新增任务</el-button>
      </div>
      <div v-loading="loadingPlans" class="day-plans-list">
        <div
          v-for="plan in selectedDayPlans"
          :key="plan.id"
          class="plan-item"
          :class="{ done: plan.status === 'DONE' }"
          @click="handlePlanClick(plan)"
        >
          <div class="plan-info">
            <div class="plan-main">
              <span class="plan-priority" :class="plan.priority.toLowerCase()">{{ plan.priority }}</span>
              <span class="plan-title">{{ plan.title }}</span>
            </div>
            <div class="plan-meta">
              <span class="plan-category">{{ categoryLabel(plan.category) }}</span>
              <span v-if="plan.estimatedMins">⏱ {{ plan.estimatedMins }}min</span>
            </div>
          </div>
          <div class="plan-status">
            <el-icon v-if="plan.status === 'DONE'" class="status-icon done"><Check /></el-icon>
            <el-icon v-else-if="plan.status === 'IN_PROGRESS'" class="status-icon inprogress"><Clock /></el-icon>
            <el-icon v-else class="status-icon todo"><CircleClose /></el-icon>
          </div>
        </div>
        <div v-if="selectedDayPlans.length === 0" class="empty-state">
          该日期暂无任务
        </div>
      </div>
    </div>

    <!-- 任务详情弹窗 -->
    <el-dialog
      v-model="showPlanDialog"
      :title="selectedPlan ? '任务详情' : '新增任务'"
      width="600px"
      destroy-on-close
    >
      <div v-if="selectedPlan" class="plan-detail">
        <div class="detail-header">
          <span class="detail-priority" :class="selectedPlan.priority.toLowerCase()">
            {{ selectedPlan.priority }}
          </span>
          <h2>{{ selectedPlan.title }}</h2>
        </div>
        <div v-if="selectedPlan.description" class="detail-desc">{{ selectedPlan.description }}</div>
        <div class="detail-meta">
          <div class="meta-item">
            <span class="meta-label">分类:</span>
            <span>{{ categoryLabel(selectedPlan.category) }}</span>
          </div>
          <div class="meta-item">
            <span class="meta-label">状态:</span>
            <span :class="`status-${selectedPlan.status.toLowerCase()}`">{{ statusLabel(selectedPlan.status) }}</span>
          </div>
          <div v-if="selectedPlan.estimatedMins" class="meta-item">
            <span class="meta-label">预估:</span>
            <span>{{ selectedPlan.estimatedMins }} 分钟</span>
          </div>
          <div v-if="selectedPlan.startTime && selectedPlan.endTime" class="meta-item">
            <span class="meta-label">时间:</span>
            <span>{{ selectedPlan.startTime }} - {{ selectedPlan.endTime }}</span>
          </div>
          <div v-if="selectedPlan.repeatType" class="meta-item">
            <span class="meta-label">重复:</span>
            <span>{{ repeatTypeLabel(selectedPlan.repeatType) }}</span>
          </div>
        </div>
        <div v-if="selectedPlan.subtaskCount && selectedPlan.subtaskCount > 0" class="detail-subtasks">
          <div class="subtask-header">
            <span>子任务进度</span>
            <span>{{ selectedPlan.completedSubtaskCount || 0 }} / {{ selectedPlan.subtaskCount }}</span>
          </div>
          <div class="subtask-progress">
            <div class="progress-bar">
              <div class="progress-fill" :style="{ width: subtaskProgress(selectedPlan) + '%' }"></div>
            </div>
          </div>
        </div>
      </div>
      <template #footer>
        <el-button @click="showPlanDialog = false">关闭</el-button>
        <el-button v-if="selectedPlan" type="primary" @click="editPlan">编辑</el-button>
        <el-button v-if="selectedPlan" type="danger" @click="deletePlan">删除</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowLeft, ArrowRight, Check, Clock, CircleClose } from '@element-plus/icons-vue'
import { planApi } from '@/api/plan'
import type { PlanItem } from '@/api/plan'
import dayjs, { Dayjs } from 'dayjs'

// ============================================================================
// // 状态
// ============================================================================

// ============================================================================
// // 状态
// ============================================================================

const emit = defineEmits<{
  (e: 'selectDate', date: string): void
}>()

const weekDays = ['日', '一', '二', '三', '四', '五', '六']
const currentMonth = ref(dayjs())
const selectedDate = ref('')
const selectedPlan = ref<PlanItem | null>(null)
const showPlanDialog = ref(false)
const calendarPlans = ref<Record<string, PlanItem[]>>({})
const loadingPlans = ref(false)

const categories = [
  { value: 'WORK', label: '工作' },
  { value: 'STUDY', label: '学习' },
  { value: 'LIFE', label: '生活' },
  { value: 'HEALTH', label: '健康' }
]

const currentMonthYear = computed(() => {
  return currentMonth.value.format('YYYY 年 MM 月')
})

const selectedDayPlans = computed(() => {
  return calendarPlans.value[selectedDate.value] || []
})

const calendarDays = computed(() => {
  const days = []
  const firstDay = currentMonth.value.startOf('month')
  const lastDay = currentMonth.value.endOf('month')
  const startWeekday = firstDay.day()
  const endWeekday = lastDay.day()

  // 上个月的日期
  const prevMonth = currentMonth.value.subtract(1, 'month')
  const prevMonthLastDay = prevMonth.endOf('month')
  for (let i = startWeekday - 1; i >= 0; i--) {
    const day = prevMonthLastDay.subtract(i, 'day')
    days.push({
      date: day.format('YYYY-MM-DD'),
      day: day.date(),
      isOtherMonth: true,
      isToday: day.isSame(dayjs(), 'day'),
      plans: calendarPlans.value[day.format('YYYY-MM-DD')] || []
    })
  }

  // 当前月的日期
  for (let i = 1; i <= lastDay.date(); i++) {
    const day = firstDay.date(i)
    days.push({
      date: day.format('YYYY-MM-DD'),
      day: i,
      isOtherMonth: false,
      isToday: day.isSame(dayjs(), 'day'),
      plans: calendarPlans.value[day.format('YYYY-MM-DD')] || []
    })
  }

  // 下个月的日期
  const nextMonth = currentMonth.value.add(1, 'month')
  for (let i = 1; i <= 6 - endWeekday; i++) {
    const day = nextMonth.date(i)
    days.push({
      date: day.format('YYYY-MM-DD'),
      day: i,
      isOtherMonth: true,
      isToday: day.isSame(dayjs(), 'day'),
      plans: calendarPlans.value[day.format('YYYY-MM-DD')] || []
    })
  }

  return days
})

function categoryLabel(val: string) {
  return categories.find(c => c.value === val)?.label || val
}

function statusLabel(val: string) {
  const labels: Record<string, string> = {
    'TODO': '待完成',
    'IN_PROGRESS': '进行中',
    'DONE': '已完成',
    'CANCELLED': '已取消'
  }
  return labels[val] || val
}

function repeatTypeLabel(val: string) {
  const labels: Record<string, string> = {
    'NONE': '不重复',
    'DAILY': '每天',
    'WEEKLY': '每周',
    'MONTHLY': '每月',
    'CUSTOM': '自定义'
  }
  return labels[val] || val
}

function subtaskProgress(plan: PlanItem) {
  if (!plan.subtaskCount || plan.subtaskCount === 0) return 0
  return Math.round(((plan.completedSubtaskCount || 0) / plan.subtaskCount) * 100)
}

function prevMonth() {
  currentMonth.value = currentMonth.value.subtract(1, 'month')
  loadMonthPlans()
}

function nextMonth() {
  currentMonth.value = currentMonth.value.add(1, 'month')
  loadMonthPlans()
}

// ============================================================================
// // 导航
// ============================================================================

// ============================================================================
// // 导航
// ============================================================================

function goToToday() {
  currentMonth.value = dayjs()
  selectDate({
    date: dayjs().format('YYYY-MM-DD')
  })
  loadMonthPlans()
}

function selectDate(day: any) {
  selectedDate.value = day.date
  emit('selectDate', day.date)
}

// ============================================================================
// // 数据加载
// ============================================================================

/**
 * 加载当月所有日期的任务数据
 *
 * 功能说明：批量加载当前月份每一天的任务列表
 * 业务逻辑：
 * 1. 获取当月第一天和最后一天日期
 * 2. 创建日期数组用于存储所有请求
 * 3. 循环为每一天创建一个API请求
 * 4. 使用Promise.all并行请求所有数据
 * 5. 将结果整理为以日期为key的对象结构：{ '2024-01-01': [Task1, Task2], ... }
 *
 * 使用场景：组件初始化、切换月份时调用
 *
 * @returns Promise<void>
 */
async function loadMonthPlans() {
  loadingPlans.value = true
  try {
    const startDate = currentMonth.value.startOf('month').format('YYYY-MM-DD')
    const endDate = currentMonth.value.endOf('month').format('YYYY-MM-DD')

    // 加载当前月所有日期的任务
    const promises: Promise<PlanItem[]>[] = []
    let current = dayjs(startDate)
    while (!current.isAfter(dayjs(endDate))) {
      promises.push(planApi.list(current.format('YYYY-MM-DD')))
      current = current.add(1, 'day')
    }

    const results = await Promise.all(promises)
    calendarPlans.value = {}
    let idx = 0
    current = dayjs(startDate)
    while (!current.isAfter(dayjs(endDate))) {
      calendarPlans.value[current.format('YYYY-MM-DD')] = results[idx] || []
      current = current.add(1, 'day')
      idx++
    }
  } catch (error) {
    console.error('Failed to load month plans', error)
  } finally {
    loadingPlans.value = false
  }
}

// ============================================================================
// // 交互处理
// ============================================================================

// ============================================================================
// // 交互处理
// ============================================================================

function handlePlanClick(plan: PlanItem) {
  selectedPlan.value = plan
  showPlanDialog.value = true
}

function handleCreatePlan() {
  emit('selectDate', selectedDate.value)
  // 触发父组件打开新建任务弹窗
  ElMessage.info('请在任务列表中创建新任务')
}

function showMorePlans(day: any) {
  selectedDate.value = day.date
  emit('selectDate', day.date)
}

function editPlan() {
  emit('selectDate', selectedDate.value)
  showPlanDialog.value = false
  // 触发父组件打开编辑任务弹窗
  ElMessage.info('请在任务列表中编辑任务')
}

async function deletePlan() {
  if (!selectedPlan.value) return

  ElMessageBox.confirm('确认删除此任务？', '提示', { type: 'warning' }).then(async () => {
    try {
      await planApi.delete(selectedPlan.value!.id)
      ElMessage.success('删除成功')
      showPlanDialog.value = false
      selectedPlan.value = null
      loadMonthPlans()
    } catch (error) {
      console.error('Failed to delete plan', error)
    }
  })
}

// ============================================================================
// // 生命周期
// ============================================================================

// ============================================================================
// // 生命周期
// ============================================================================

onMounted(() => {
  selectedDate.value = dayjs().format('YYYY-MM-DD')
  loadMonthPlans()
})
</script>

<style lang="scss" scoped>
.calendar-view {
  display: flex;
  flex-direction: column;
  gap: 20px;

  .calendar-header {
    display: flex;
    align-items: center;
    gap: 16px;

    .current-month {
      font-size: 18px;
      font-weight: 600;
      color: $text-primary;
      min-width: 120px;
      text-align: center;
    }
  }

  .calendar-grid {
    background: $bg-card;
    border: 1px solid $border;
    border-radius: $radius-md;
    overflow: hidden;

    .week-header {
      display: grid;
      grid-template-columns: repeat(7, 1fr);
      background: rgba(99, 102, 241, 0.05);
      border-bottom: 1px solid $border;

      .weekday {
        padding: 12px;
        text-align: center;
        font-weight: 600;
        color: $text-secondary;
      }
    }

    .calendar-body {
      display: grid;
      grid-template-columns: repeat(7, 1fr);
      grid-auto-rows: minmax(100px, 1fr);

      .calendar-day {
        border-right: 1px solid $border;
        border-bottom: 1px solid $border;
        padding: 8px;
        cursor: pointer;
        transition: $transition-fast;
        min-height: 100px;

        &:hover {
          background: rgba(99, 102, 241, 0.05);
        }

        &.other-month {
          opacity: 0.3;
        }

        &.today {
          background: rgba(99, 102, 241, 0.08);
        }

        &.selected {
          background: rgba(99, 102, 241, 0.15);
          border-color: $primary;
        }

        .day-number {
          font-size: 14px;
          font-weight: 600;
          color: $text-primary;
          margin-bottom: 8px;
        }

        .day-plans {
          display: flex;
          flex-direction: column;
          gap: 4px;

          .plan-chip {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 11px;
            cursor: pointer;
            transition: $transition-fast;
            border-left: 3px solid;

            &.priority-p0 { background: rgba(239, 68, 68, 0.1); border-left-color: #ef4444; }
            &.priority-p1 { background: rgba(249, 115, 22, 0.1); border-left-color: #f97316; }
            &.priority-p2 { background: rgba(59, 130, 246, 0.1); border-left-color: #3b82f6; }
            &.priority-p3 { background: rgba(107, 114, 128, 0.1); border-left-color: #6b7280; }

            &.done {
              opacity: 0.5;
              text-decoration: line-through;
            }

            &:hover {
              transform: translateX(2px);
            }

            .plan-title {
              flex: 1;
              overflow: hidden;
              text-overflow: ellipsis;
              white-space: nowrap;
            }

            .plan-subtask {
              font-size: 10px;
              color: $text-secondary;
              margin-left: 4px;
            }
          }

          .more-plans {
            font-size: 11px;
            color: $primary;
            cursor: pointer;
            text-align: center;
            padding: 2px;

            &:hover {
              text-decoration: underline;
            }
          }
        }
      }
    }
  }

  .day-details {
    background: $bg-card;
    border: 1px solid $border;
    border-radius: $radius-md;
    padding: 20px;

    .details-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 16px;

      h3 {
        margin: 0;
        font-size: 16px;
        font-weight: 600;
        color: $text-primary;
      }
    }

    .day-plans-list {
      display: flex;
      flex-direction: column;
      gap: 8px;

      .plan-item {
        display: flex;
        align-items: center;
        gap: 12px;
        padding: 12px;
        background: rgba(255, 255, 255, 0.03);
        border: 1px solid $border;
        border-radius: $radius-sm;
        cursor: pointer;
        transition: $transition-fast;

        &:hover {
          border-color: $primary;
          background: rgba(99, 102, 241, 0.05);
        }

        &.done {
          opacity: 0.6;
          .plan-main .plan-title {
            text-decoration: line-through;
          }
        }

        .plan-info {
          flex: 1;

          .plan-main {
            display: flex;
            align-items: center;
            gap: 8px;
            margin-bottom: 4px;

            .plan-priority {
              font-size: 11px;
              font-weight: 600;
              padding: 2px 6px;
              border-radius: 4px;

              &.p0 { background: rgba(239, 68, 68, 0.2); color: #ef4444; }
              &.p1 { background: rgba(249, 115, 22, 0.2); color: #f97316; }
              &.p2 { background: rgba(59, 130, 246, 0.2); color: #3b82f6; }
              &.p3 { background: rgba(107, 114, 128, 0.2); color: #6b7280; }
            }

            .plan-title {
              font-size: 14px;
              font-weight: 500;
              color: $text-primary;
            }
          }

          .plan-meta {
            display: flex;
            gap: 12px;
            font-size: 12px;
            color: $text-secondary;

            .plan-category {
              padding: 2px 6px;
              background: rgba(99, 102, 241, 0.1);
              border-radius: 4px;
              color: #6366f1;
            }
          }
        }

        .plan-status {
          .status-icon {
            font-size: 20px;

            &.done { color: $success; }
            &.inprogress { color: $warning; }
            &.todo { color: $text-muted; }
          }
        }
      }

      .empty-state {
        text-align: center;
        padding: 40px 20px;
        color: $text-muted;
      }
    }
  }
}

.plan-detail {
  .detail-header {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 16px;

    .detail-priority {
      font-size: 12px;
      font-weight: 600;
      padding: 4px 8px;
      border-radius: 4px;

      &.p0 { background: rgba(239, 68, 68, 0.2); color: #ef4444; }
      &.p1 { background: rgba(249, 115, 22, 0.2); color: #f97316; }
      &.p2 { background: rgba(59, 130, 246, 0.2); color: #3b82f6; }
      &.p3 { background: rgba(107, 114, 128, 0.2); color: #6b7280; }

      h2 {
        margin: 0;
        font-size: 18px;
        font-weight: 600;
        color: $text-primary;
      }
    }
  }

  .detail-desc {
    color: $text-secondary;
    margin-bottom: 20px;
    line-height: 1.6;
  }

  .detail-meta {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 12px;
    margin-bottom: 20px;

    .meta-item {
      display: flex;
      gap: 8px;

      .meta-label {
        color: $text-secondary;
        min-width: 60px;
      }

      .status-todo { color: #64748b; }
      .status-in_progress { color: #f59e0b; }
      .status-done { color: #10b981; }
      .status-cancelled { color: #ef4444; }
    }
  }

  .detail-subtasks {
    background: rgba(255, 255, 255, 0.03);
    border-radius: $radius-sm;
    padding: 12px;

    .subtask-header {
      display: flex;
      justify-content: space-between;
      margin-bottom: 8px;
      font-size: 14px;
      color: $text-primary;
    }

    .subtask-progress {
      .progress-bar {
        height: 6px;
        background: rgba(255, 255, 255, 0.1);
        border-radius: 3px;
        overflow: hidden;

        .progress-fill {
          height: 100%;
          background: $primary;
          transition: width 0.3s ease;
        }
      }
    }
  }
}
</style>
